### ISSUE TITLE
Slicing profile fix for 1.1.2

### ISSUE THREAD

**Issue by victorevector** [Robo3D/Update_Script#11]
# Issue

There isn't a clear instruction for what profiles the printer's should have. This has led to me to ship our printers with deprecated profiles. 

# Recommended option

Profile management occurs in this repository: https://github.com/Robo3D/Slicing-Profiles. All onboard slicing profiles will be kept and maintained in this folder: https://github.com/Robo3D/Slicing-Profiles/tree/master/Cura%2015.04.6. Let's use versioning/releases to track releases and map them to roboOS versions. 

# Next steps

@AllenMcAfee @CobyKabili  Who should be in charge of maintaining this repository? I'll collaborate with them to make sure all printer's receive official profiles.

**Comment by CobyKabili** [comment]
@victorevector are you saying the onboard slicing will pull directly from these profiles when updating? 

example - no profiles in the https://github.com/Robo3D/Slicing-Profiles/tree/master/Cura%2015.04.6/C2 then a user will not be able to slice on board? If we update that file, every file will slice with those exact settings?

**Comment by victorevector** [comment]
@CobyKabili No, I am saying that we ship the printers with pre-installed slicing profiles ([found here](https://github.com/Robo3D/buildScriptOS/tree/master/assets/cura) ), and I source those profiles from the directory you mentioned. 

I can also send profiles to printers in the wild via our update system.

**Comment by CobyKabili** [comment]
Lets walk through these profiles tomorrow and make sure we are updating both profiles. I will get with @JasonBarretto and @ROBOLabs to make sure we have the most up-to-date profile to log into that repo.

Whats the timeline of the onboard slicing roll out?

**Comment by victorevector** [comment]
@CobyKabili We already support onboard slicing via the webapp, so we'll need the profile(s) by tomorrow (Thursday 2/15) to fulfill our R2 deadline. 

With regards to the slicing wizard, we're shipping it with RoboLCD 1.4.0, which doesn't have a shipment date yet.

**Comment by victorevector** [comment]
Pushing this update for a later date when we release robolcd 1.4.0 which supports onboard slicing
