### ISSUE TITLE
C2 update gcode files

### ISSUE THREAD

**Issue by CobyKabili** [Robo3D/Update_Script#15]
Here are the gcodes that were requested

[GCode.zip](https://github.com/Robo3D/Update_Script/files/800655/GCode.zip)

**Comment by victorevector** [comment]
&& remove the following files:

1. robo_keychain.gcode

2. smartphone_and_tablet_stand.gcode

3. wavy_vase.gcode

4. Whistle_V29D.gcode

5. TEST(skirt_no_raft).gcode

6. TEST(with_raft).gcode
