### ISSUE TITLE
1.5.0 update

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/Update_Script#44]
- RoboLCD
- Filament-Sensor
- Meta-Reader
- Gcode for benchy (C2 Only)
[RC_3DBenchy.gcode.zip](https://github.com/Robo3D/Update_Script/files/1043153/RC_3DBenchy.gcode.zip)
 @AllenMcAfee @CobyKabili @victorevector Please edit as necessary

**Comment by victorevector** [comment]
benchy c2
